# src/main/resources/application.yml

server:
  port: 8081

spring:
  application:
    name: camera-service

  # ??????????? ? PostgreSQL ????? R2DBC
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mvd_db
    username: postgres
    password: postgres  # ? ?????? ?? ???? ??????

  data:
    r2dbc:
      repositories:
        enabled: true

  # ?????????????? ?????????? schema.sql
  sql:
    init:
      mode: always


## Eureka (???? ???????????)
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost

# ???????????
logging:
  level:
    org.springframework.r2dbc: DEBUG
    com.example.cameraservice: DEBUG
