# object-service/src/main/resources/application.yml

server:
  port: 8082

spring:
  application:
    name: object-service

  # ??????????? ? PostgreSQL ????? JPA
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: postgres  # ? ?????? ?? ???? ??????
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # ????????????? ??????? ???????
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # ?????????????? ?????????? data.sql (???? ????)
  sql:
    init:
      mode: always

## Eureka
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost

# ???????????
logging:
  level:
    org.hibernate.SQL: DEBUG
    com.example.objactservice: DEBUG